(deftheme igord
  "Created 2014-03-31.")

(custom-theme-set-variables
 'igord
 '(ansi-color-names-vector ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(browse-url-browser-function (quote browse-url-generic))
 '(browse-url-generic-program "firefox")
 '(c-basic-offset 4)
 '(c-default-style (quote ((c-mode . "k&r") (c++-mode . "k&r") (java-mode . "java") (other . "gnu"))))
 '(compilation-scroll-output t)
 '(default-input-method "ukrainian-computer-ext")
 '(default-justification (quote full))
 '(dired-guess-shell-alist-user (quote ((".*\\.djvu$" "djview ? &"))))
 '(dired-listing-switches "-alDh")
 '(font-lock-maximum-decoration t)
 '(font-lock-support-mode (quote jit-lock-mode))
 '(haskell-literate-default (quote latex))
 '(indent-tabs-mode nil)
 '(inferior-lisp-program "sbcl")
 '(load-home-init-file t)
 '(safe-local-variable-values (quote ((make-backup-files . t) (trim-versions-without-asking))))
 '(scalable-fonts-allowed nil)
 '(scroll-bar-mode (quote right))
 '(show-paren-delay 0)
 '(show-paren-style (quote expression))
 '(tab-width 8)
 '(tex-dvi-view-command (quote (cond ((eq window-system (quote x)) "kdvi") ((eq window-system (quote w32)) "yap") (t "dvi2tty * | cat -s"))))
 '(truncate-lines t)
 '(undo-limit 2000000)
 '(transient-mark-mode t)
 '(show-paren-mode t)
 '(highlight-symbol-mode t)
 '(global-font-lock-mode t)
 '(custom-safe-themes (quote ("3f8774f3f8568e73d550aa871320dc4979c00ae4a65bd2e076d216364cc87883" default))))

(custom-theme-set-faces
 'igord
 '(erin-heading-1-face ((t (:weight bold :height 2.48832 :family "Sans"))))
 '(erin-heading-2-face ((t (:weight bold :height 2.0736 :family "Sans"))))
 '(erin-heading-3-face ((t (:weight bold :height 1.728 :family "Sans"))))
 '(erin-heading-4-face ((t (:weight bold :height 1.44 :family "Sans"))))
 '(erin-heading-5-face ((t (:weight bold :height 1.2 :family "Sans"))))
 '(erin-heading-6-face ((t (:weight bold :height 1.0 :family "Sans"))))
 '(paren-face-match ((t (:background "dark green"))))
 '(paren-face-mismatch ((t (:background "red"))))
 '(paren-match ((t (:background "forest green"))))
 '(paren-mismatch ((t (:background "red"))))
 '(show-paren-match ((t (:background "dark green"))))
 '(show-paren-mismatch ((t (:background "red1"))))
 '(Info-title-1-face ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.728))))
 '(Info-title-2-face ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.44))))
 '(Info-title-3-face ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.2))))
 '(Info-title-4-face ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "Red1"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight normal :foreground "LightSkyBlue"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(cperl-array-face ((((class color) (min-colors 89)) (:foreground "yellow2"))))
 '(cperl-hash-face ((((class color) (min-colors 89)) (:foreground "coral1"))))
 '(cursor ((((class color) (min-colors 89)) (:background "green"))))
 '(diff-added ((((class color) (min-colors 89)) (nil))))
 '(diff-changed ((((class color) (min-colors 89)) (nil))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "seashell4"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "grey60"))))
 '(diff-function ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-header ((((class color) (min-colors 89)) (:background "grey45"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-index ((((class color) (min-colors 89)) (:inherit diff-file-header))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "white" :background "darkolivegreen"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:foreground "white" :background "dodgerblue4"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "white" :background "indianred4"))))
 '(diff-refine-change ((((class color) (min-colors 89)) (:background "skyblue4"))))
 '(diff-removed ((((class color) (min-colors 89)) (nil))))
 '(dired-marked ((((class color) (min-colors 89)) (:background "dodgerblue3" :foreground "white"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:background "green4" :foreground "white"))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:background "darkorange3" :foreground "white"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "Grey50" :foreground "White"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background "skyblue4" :foreground "white"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background "cyan4" :foreground "white"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "Grey50" :foreground "White"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:background nil :underline "red"))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:background nil :underline "magenta3"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-doc-string-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-reference-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 ;'(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "burlywood"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#b1d631"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(fringe ((((class color) (min-colors 89)) (:background "black"))))
 '(highlight ((((class color) (min-colors 89)) (:background "DodgerBlue4"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:weight normal :foreground "orange"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "green"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-keyword-face))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(isearch ((((class color) (min-colors 89)) (:background "coral2" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "cadetblue" :foreground "white"))))
 '(match ((t (:background "DeepPink4"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "gray75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "blue4"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "gray40" :foreground "black" :box (:line-width 1 :color "gray40" :style nil)))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "SkyBlue1"))))
 '(outline-2 ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "LightSteelBlue1"))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "turquoise2"))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "aquamarine1"))))
 '(primary-selection ((((class color) (min-colors 89)) (:background "blue3"))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "Yellow"))))
 ;'(default ((((class color) (min-colors 89)) (:background "#181a26" :foreground "gray80")))) 
 '(default ((((class color) (min-colors 89)) (:background "#1c1c1c" :foreground "#dadada")))))

(provide-theme 'igord)
